# Database stores all the settings releated
# to the database connection that the ORM
# will use in order to provide it's functionality
# ===============================================

# Determines the driver to use
# Possible options are:
# 'mysql', 'postgres', 'sqlite3'.
driver = "sqlite3"

# Database represents the database name
# to use or the database path in case of
# using sqlite3 driver. If driver is sqlire3
# the value ':memory:' can also be used to create
# a temp database stored in memory.
database = "./sample.db"

# Host represents the database host where
# it will connect to. Unused if using
# the sqlite3 driver.
host = "localhost"

# Port represents the database port where
# it will connect to. Unused if using
# the sqlite3 driver.
port = "3306"

# User represents the user used to establish
# the database connection. Unused if using
# the sqlite3 driver.
user = "sample"

# Password represents the password used to establish
# the database connection. Unused if using
# the sqlite3 driver.
password = "secret"

# Auto migrate is used to migrate the database shema
# using the provided models. It will ONLY create tables,
# missing columns and missing indexes, and WON’T change
# existing column’s type or delete unused columns
# to protect your data.
auto_migrate = true
